version: 2

updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
          day: monday
          time: "08:00"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - github-actions

    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
          day: monday
          time: "08:15"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - npm

    - package-ecosystem: npm
      directory: /frontend
      schedule:
          interval: weekly
          day: monday
          time: "08:30"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - npm

    - package-ecosystem: pip
      directory: /backend
      schedule:
          interval: weekly
          day: monday
          time: "08:45"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - python

    - package-ecosystem: docker
      directory: /
      schedule:
          interval: weekly
          day: monday
          time: "09:00"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - docker

    - package-ecosystem: docker
      directory: /docker/backend
      schedule:
          interval: weekly
          day: monday
          time: "09:15"
      open-pull-requests-limit: 5
      labels:
          - dependencies
          - docker
